name: Actualizar RSS

on:
  schedule:
    - cron: '0 0 * * *'  # Esto corre una vez al día a medianoche UTC
  workflow_dispatch:      # Permite ejecutar manualmente también

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Mensaje de prueba
        run: echo "GitHub Actions configurado correctamente"
